---
- include: create_volume.yml
  when: docker_volume_device is defined

- include: el7.yml
  when: ansible_os_family | lower == 'redhat'

- include: debian.yml
  when: ansible_os_family | lower == 'debian'

- name: Ensure the Docker group exists.
  group:
    name: docker
    state: present
